name: Pytest
on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Nim on Mac OS
      run: |
        brew install nim

    - name: Install Nim dependencies
      run: |
        nimble install -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]

    - name: Test with pytest
      run: |
        python -m pytest tests/

    - name: Test nim
      run: |
        nimble test
