name: Pytest
on: [push, pull_request]

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Nim on Mac OS
      if: runner.os == 'macOS'
      run: |
        brew install nim

    - name: Install Nim
      if: runner.os == 'Linux'
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.2.4'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nim dependencies
      run: |
        nimble install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        python -m pytest tests/
