name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout without new path
        uses: actions/checkout@v4
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: Checkout with new path # issue with windows path too long during compilation
        if: runner.os == 'Windows'
        with:
          path: C:/tmp

      - name: Install Nim on Mac OS
        if: runner.os == 'macOS'
        run: |
          brew install nim

      - name: Install Nim
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Wheels
        run: |
          nimble install -y
          python -m build
