name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nim on Mac OS
        if: runner.os == 'macOS'
        run: |
          brew install nim

      - name: Install Nim
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          nimble install -y

      - name: Build Wheels
        run: |
          python -m build
